CUDA_VISIBLE_DEVICES=0 python train_gpt_xtts.py \
--output_path checkpoints/ \
--metadatas processed_data/metadata_train.csv,processed_data/metadata_eval.csv,vi \
--num_epochs 50 \
--batch_size 8 \
--grad_acumm 4 \
--max_text_length 400 \
--max_audio_length 330750 \
--weight_decay 1e-2 \
--lr 1e-4 \
--save_step 50000